//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerInterestedInCours
    {
        public int TrainerInterested { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<int> Course { get; set; }
    
        public virtual Course Course1 { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
